// Copyright 2026 Schuby
// SPDX-License-Identifier: Apache-2.0

/**
 * Binary lane — generator. Distils the per-version symbol extractions (produced
 * by `scripts/extract-bundle.ts` over every archived Claude Code binary) into
 * one committed, auditable evidence file: `data/binary-observations.json`.
 *
 * Evidence, not policy. This file records only *what was observed* — for each
 * own-evidenced symbol, the earliest and latest archived version whose bundle
 * contained it, plus the exact set of versions scanned (`observedVersions`).
 * The interpretation of that evidence (which symbols to publish, how to
 * categorize them, when to correct a `first_seen`) lives in the overlay,
 * `scripts/binary-lane.ts`, so the raw observations stay provenance-clean.
 *
 * `removed_in` is derived conservatively (see binary-lane's computeBinaryRemoval):
 * only a clean disappearance in the RELIABLE extraction era (< ~2.1.160) sets it.
 * Late-era absence is unreliable — the extractor's recall regressed around 2.1.160
 * (see scratch/audit-buckets.md), so a symbol last seen there is left present, and
 * the changelog remains the authority for confirmed (changelog/docs) symbols'
 * removals. Interior per-version on/off history is not encoded.
 *
 * Input = the per-version cache `binary-cache/<version>.json`, a COMMITTED
 * artifact (small JSON; the 139 GB binary archive it derives from is not). Run
 * this to regenerate `data/binary-observations.json` after the cache gains a
 * version — whether from the maintainer-local `reextract-binaries` (full,
 * archive-backed) or the CI `scrape-binary` (one release, CDN-backed). Because
 * the cache is committed, CI can re-distill with no binaries or re-download.
 */
import { existsSync } from 'node:fs';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import {
  computeBinaryRemoval,
  type BinaryDescriptions,
  type BinaryObservation,
  type BinaryObservations,
  type DescriptionEra,
} from './binary-lane.js';
import { compareVersionsAsc, type ExtractedSymbolType, isMain } from './lib.js';
import type { ControlObservation, Era } from './binary-lane.js';
import { CACHE_INCOMPLETE_MARKER } from './reextract-binaries.js';

/** One per-version extraction file: `binary-cache/<version>.json`. */
export interface BinaryCacheFile {
  version: string;
  source?: string;
  count?: number;
  symbols: Array<{
    symbol: string;
    type: ExtractedSymbolType;
    category?: string;
    evidence?: string;
    description?: string;
    /**
     * Distilled, unlike the cache-only fields above. Scope is evidence the bundle
     * itself carries (the parser module's `Usage: claude <path>` banner), not an
     * interpretation layered on top, so it belongs in the observation file — the
     * publish/withhold decision it feeds still lives in binary-lane.ts.
     */
    scopes?: readonly string[];
    /** Registered with commander's `.hideHelp()` in this version. */
    hidden?: true;
  }>;
  /** Written by both cache writers; absent in a cache predating the control lane. */
  controlMessages?: ReadonlyArray<{
    symbol: string;
    family: 'control_request';
    direction: 'host_to_cli' | 'cli_to_host' | null;
    description: string;
    evidence: 'schema' | 'call_site' | 'dispatch';
    admittedBy: 'union' | 'dispatch' | 'both';
  }>;
}

const NOTE =
  'Per-symbol observation window across archived Claude Code binaries. ' +
  'first_seen/last_seen are the earliest/latest scanned versions whose bundle ' +
  'contained the symbol (positive extraction evidence). removed_in is a conservative ' +
  'cliff-aware estimate: set only for a clean disappearance in the reliable extraction ' +
  'era (< ~2.1.160); later absence is untrusted (recall regressed there) and left null. ' +
  'Generated by scripts/backfill-binary.ts; interpreted by scripts/binary-lane.ts.';

const CONTROL_NOTE =
  'Per-subtype observation window for the stream-json control protocol, across the ' +
  'archived binaries. direction_eras and description_eras are CHANGE POINTS: each holds ' +
  'from its `from` version until the next, because both values move. Resolve with ' +
  'eraValueAt — never read the last entry as the current answer for an older snapshot. ' +
  'admitted_at_first_seen is the signal that admitted the subtype AT first_seen, which ' +
  'is what makes that date checkable; `union` means it is an upper bound. Generated by ' +
  'scripts/backfill-binary.ts; interpreted by scripts/binary-lane.ts.';

const DEFAULT_CACHE_DIR = 'binary-cache';
const DEFAULT_OUT_PATH = 'data/binary-observations.json';

/** Sorts symbols deterministically by type then symbol name (matches other lanes). */
function compareObservations(a: BinaryObservation, b: BinaryObservation): number {
  if (a.type !== b.type) return a.type < b.type ? -1 : 1;
  if (a.symbol < b.symbol) return -1;
  /* v8 ignore next -- observations are unique per type:symbol key, so equality cannot occur */
  if (a.symbol === b.symbol) return 0;
  return 1;
}

/**
 * Reduces the per-version cache files to one observation window per symbol.
 * Pure (no fs) so it is unit-testable against in-memory fixtures. A symbol's
 * `first_seen` is the numerically-earliest version it appears in, `last_seen`
 * the latest, and `removed_in` a conservative cliff-aware disappearance estimate
 * (see computeBinaryRemoval; null for symbols still present or too noisy to judge).
 * `observedVersions` is the full scanned set, newest first.
 */
export function distillObservations(files: BinaryCacheFile[]): BinaryObservations {
  const observedVersions = files
    .map((file) => file.version)
    .sort((a, b) => compareVersionsAsc(b, a));

  // Collect every version each symbol was seen in, then derive the window.
  const seenIn = new Map<
    string,
    {
      symbol: string;
      type: ExtractedSymbolType;
      versions: string[];
      strongEvidence: boolean;
      scopes: Set<string>;
      /** Versions that registered the flag as hidden, collapsed into eras below. */
      hiddenIn: Set<string>;
    }
  >();
  for (const file of files) {
    for (const { symbol, type, evidence, scopes, hidden } of file.symbols) {
      const key = `${type}:${symbol}`;
      // Evidence is per-version and can strengthen over releases (a flag parsed by a
      // switch in one release may be commander-registered in the next). Track whether
      // ANY version proved it by something other than a switch-case label, so the
      // scope caveat is dropped the moment better evidence exists.
      const strong = evidence !== 'argv-switch';
      const entry = seenIn.get(key);
      if (entry) {
        entry.versions.push(file.version);
        entry.strongEvidence ||= strong;
        for (const s of scopes ?? []) entry.scopes.add(s);
        if (hidden) entry.hiddenIn.add(file.version);
      } else
        seenIn.set(key, {
          symbol,
          type,
          versions: [file.version],
          strongEvidence: strong,
          scopes: new Set(scopes ?? []),
          hiddenIn: new Set(hidden ? [file.version] : []),
        });
    }
  }

  const symbols: BinaryObservation[] = [];
  for (const { symbol, type, versions, strongEvidence, scopes, hiddenIn } of seenIn.values()) {
    const sorted = [...versions].sort(compareVersionsAsc);
    // Visibility is a TIMELINE, not a current state. Six flags flip between
    // hidden and public across the archive (--teleport, --task-budget, --cloud,
    // --interactive, --max-budget-usd, --remote-control), so collapsing to the
    // latest value would stamp today's answer on every historical snapshot —
    // the same defect the config_key category and the scopes field each had.
    // Only change points are emitted, and only when the flag was ever hidden.
    const hiddenEras: { from: string; hidden: boolean }[] = [];
    for (const v of sorted) {
      const isHidden = hiddenIn.has(v);
      if (hiddenEras[hiddenEras.length - 1]?.hidden !== isHidden) {
        hiddenEras.push({ from: v, hidden: isHidden });
      }
    }
    // A leading "not hidden" era carries no information — absence says the same.
    if (hiddenEras[0]?.hidden === false) hiddenEras.shift();
    symbols.push({
      symbol,
      type,
      first_seen: sorted[0] as string,
      last_seen: sorted[sorted.length - 1] as string,
      removed_in: computeBinaryRemoval(versions, observedVersions),
      ...(hiddenEras.length ? { hidden_eras: hiddenEras } : {}),
      // Scope rides with the caveat it lifts. A symbol with strong evidence
      // somewhere publishes top-level, and narrowing it by a subcommand parser
      // that accepts the same name would be a false claim, not a refinement.
      ...(strongEvidence
        ? {}
        : {
            switch_case_only: true as const,
            ...(scopes.size ? { scopes: [...scopes].sort() } : {}),
          }),
    });
  }

  return {
    $generated_by: 'scripts/backfill-binary.ts',
    source: 'binary',
    note: NOTE,
    observedVersions,
    symbols: symbols.sort(compareObservations),
  };
}

const DESC_NOTE =
  'Per-symbol description timeline across archived Claude Code binaries: the ' +
  'command/skill registry description captured per version, collapsed to change ' +
  'points (eras). Each era holds from the given version until the next. Lets a ' +
  'snapshot carry the description the symbol actually had at that version instead ' +
  'of one current string. Generated by scripts/backfill-binary.ts; consumed by ' +
  'scripts/scrape-changelog.ts.';

/**
 * Distills a per-symbol description timeline from the cache: for every symbol that
 * carries a registry description, collect (version, description) across all cache
 * files and collapse consecutive-equal descriptions into eras (a new era only when
 * the text changes). A recall gap (a version that missed the symbol) is spanned by
 * the surrounding era — the same version-bounded imprecision as first_seen.
 */
/**
 * Collapse runs of repeated spaces and trim the ends. A cosmetic spacing change in
 * the source (e.g. "Maximum thinking tokens.  (only…" → "…tokens. (only…", a double
 * space becoming single) is NOT a real description change, so normalizing here stops
 * it spawning a spurious "duplicate-looking" era. Only repeated SPACES are collapsed
 * — newlines and tabs are left intact so a genuinely multi-line description (an
 * indented option list / example that cleanDescription preserves) keeps its structure
 * and is not flattened or merged with a differently-structured era. cleanDescription
 * (the extractor) remains the authoritative content filter.
 */
function normalizeDescriptionWhitespace(text: string): string {
  return text.replace(/ {2,}/g, ' ').trim();
}

export function distillDescriptions(files: BinaryCacheFile[]): BinaryDescriptions {
  const seen = new Map<string, Array<{ version: string; description: string }>>();
  for (const file of files) {
    for (const s of file.symbols) {
      // The extractor (cleanDescription) is the authoritative description filter —
      // it drops backtick TEMPLATE literals but KEEPS a static quoted string that
      // merely contains "${". Don't re-filter `${` here: the cache no longer carries
      // the delimiter, so a broader `${` skip would wrongly drop a valid static one.
      if (!s.description) continue;
      const key = `${s.type}:${s.symbol}`;
      const arr = seen.get(key) ?? [];
      arr.push({
        version: file.version,
        description: normalizeDescriptionWhitespace(s.description),
      });
      seen.set(key, arr);
    }
  }

  const descriptions: Record<string, DescriptionEra[]> = {};
  for (const key of [...seen.keys()].sort()) {
    const observations = [
      ...(seen.get(key) as Array<{ version: string; description: string }>),
    ].sort((a, b) => compareVersionsAsc(a.version, b.version));
    const eras: DescriptionEra[] = [];
    for (const obs of observations) {
      const last = eras[eras.length - 1];
      if (!last || last.description !== obs.description) {
        eras.push({ from: obs.version, description: obs.description });
      }
    }
    descriptions[key] = eras;
  }

  return {
    $generated_by: 'scripts/backfill-binary.ts',
    source: 'binary',
    note: DESC_NOTE,
    descriptions,
  };
}

/**
 * Control-request subtypes distilled across the archive, one entry per subtype.
 *
 * Mirrors `distillObservations`: same window derivation, same removal rule, and the
 * same change-point treatment for anything that moves. What moves here is `direction`
 * (null everywhere until the CLI declared the two directional unions at 2.1.133) and
 * `description` (absent before 2.1.63, rewordable after), so both are eras.
 */
export function distillControlObservations(files: BinaryCacheFile[]): ControlObservation[] {
  const observedVersions = files
    .map((file) => file.version)
    .sort((a, b) => compareVersionsAsc(b, a));

  type Direction = ControlObservation['direction_eras'][number]['value'];
  type Evidence = ControlObservation['evidence_eras'][number]['value'];
  type Family = ControlObservation['family'];
  type PerVersion = {
    family: Family;
    direction: Direction;
    description: string;
    evidence: Evidence;
    admittedBy: ControlObservation['admitted_at_first_seen'];
  };
  const seenIn = new Map<string, { symbol: string; byVersion: Map<string, PerVersion> }>();

  for (const file of files) {
    for (const message of file.controlMessages ?? []) {
      const entry = seenIn.get(message.symbol) ?? { symbol: message.symbol, byVersion: new Map() };
      entry.byVersion.set(file.version, {
        family: message.family,
        direction: message.direction,
        description: message.description,
        evidence: message.evidence,
        admittedBy: message.admittedBy,
      });
      seenIn.set(message.symbol, entry);
    }
  }

  const observations: ControlObservation[] = [];
  for (const { symbol, byVersion } of seenIn.values()) {
    const versions = [...byVersion.keys()].sort(compareVersionsAsc);
    const firstSeen = versions[0] as string;

    // Change points only, walked oldest-first. `undefined` as the seed rather than a
    // real value so the first version always emits an era — otherwise a subtype whose
    // direction starts as null would have no era at all and the resolver's fallback
    // would be doing the work silently.
    const directionEras: Array<Era<Direction>> = [];
    const descriptionEras: Array<Era<string>> = [];
    const evidenceEras: Array<Era<Evidence>> = [];
    let lastDirection: Direction | undefined;
    let lastDescription: string | undefined;
    let lastEvidence: Evidence | undefined;
    for (const version of versions) {
      const at = byVersion.get(version) as PerVersion;
      if (lastDirection === undefined || at.direction !== lastDirection) {
        directionEras.push({ from: version, value: at.direction });
        lastDirection = at.direction;
      }
      if (lastDescription === undefined || at.description !== lastDescription) {
        descriptionEras.push({ from: version, value: at.description });
        lastDescription = at.description;
      }
      if (lastEvidence === undefined || at.evidence !== lastEvidence) {
        evidenceEras.push({ from: version, value: at.evidence });
        lastEvidence = at.evidence;
      }
    }

    const family = (byVersion.get(firstSeen) as PerVersion).family;
    // Carried from the cache, not hardcoded, so a widened family enum cannot relabel a
    // subtype silently. Read at first_seen like `admitted_at_first_seen`; a subtype
    // must not change family across the window (that would be a value that varies by
    // version with no era), so disagreement throws rather than picking one.
    for (const [version, at] of byVersion) {
      if (at.family !== family) {
        throw new Error(
          `${symbol}: family is ${JSON.stringify(at.family)} at ${version} but ` +
            `${JSON.stringify(family)} at ${firstSeen}. A control subtype must not ` +
            `change family across versions.`
        );
      }
    }

    observations.push({
      symbol,
      family,
      first_seen: firstSeen,
      last_seen: versions[versions.length - 1] as string,
      removed_in: computeBinaryRemoval(versions, observedVersions),
      direction_eras: directionEras,
      description_eras: descriptionEras,
      evidence_eras: evidenceEras,
      // At first_seen, NOT at the newest version: a subtype that starts as `union`
      // usually becomes `both` later, and reading the current value would un-flag it.
      admitted_at_first_seen: (byVersion.get(firstSeen) as PerVersion).admittedBy,
    });
  }

  return observations.sort((a, b) => a.symbol.localeCompare(b.symbol));
}

/** Loads every `<version>.json` cache file from a directory. */
export async function loadCacheFiles(dir: string): Promise<BinaryCacheFile[]> {
  const names = (await readdir(dir)).filter(
    (name) => name.endsWith('.json') && !name.startsWith('_')
  );
  const files = await Promise.all(
    names.map(
      async (name) => JSON.parse(await readFile(join(dir, name), 'utf-8')) as BinaryCacheFile
    )
  );
  if (files.length === 0) {
    throw new Error(
      `No cache files in ${dir}. The binary archive/cache is a maintainer-local artifact; ` +
        `rebuild it (see scratch/backfill-notes.md) before regenerating the observations.`
    );
  }
  // "Zero files" is not enough: a partly-written cache is indistinguishable from a
  // complete one by its listing alone, so this reads the marker the re-extract leaves.
  const marker = join(dir, CACHE_INCOMPLETE_MARKER);
  if (existsSync(marker)) {
    throw new Error(
      `${marker} exists: the cache is not known to be complete. Read it — its ` +
        `\`status\` is in-progress (interrupted), refused (a lane could not read a ` +
        `bundle) or skipped (versions are missing from the cache, possibly because ` +
        `the archive no longer has them). Distilling now would report those versions' ` +
        `symbols as removed. Fix the cause the file names — a re-run alone does not ` +
        `clear a \`skipped\` flag, because the archive is what is short — and only ` +
        `backfill once the marker is gone.`
    );
  }
  return files;
}

interface CliOptions {
  cacheDir: string;
  outPath: string;
  control: boolean;
}

function parseArgs(argv: string[]): CliOptions {
  const options: CliOptions = {
    cacheDir: DEFAULT_CACHE_DIR,
    outPath: DEFAULT_OUT_PATH,
    control: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--control') options.control = true;
    if (arg === '--cache' || arg === '--out') {
      const value = argv[i + 1];
      if (value === undefined) {
        throw new Error(`${arg} requires a path argument (e.g. "${arg} <dir>").`);
      }
      if (arg === '--cache') options.cacheDir = value;
      else options.outPath = value;
      i++;
    }
  }
  return options;
}

export async function main(argv: string[]): Promise<number> {
  const options = parseArgs(argv);
  const files = await loadCacheFiles(options.cacheDir);

  const observations = distillObservations(files);
  await writeFile(options.outPath, `${JSON.stringify(observations, null, 2)}\n`, 'utf-8');

  // The description timeline is written alongside the observations (same dir), so
  // a scratch --out during tests keeps both outputs out of committed data/.
  const descriptions = distillDescriptions(files);
  const descPath = join(dirname(options.outPath), 'binary-descriptions.json');
  await writeFile(descPath, `${JSON.stringify(descriptions, null, 2)}\n`, 'utf-8');

  // A sibling file rather than a section of the observations, mirroring the
  // descriptions above: control_message is a different symbol type with its own
  // shape, and widening binary-observations.json would change a file every consumer
  // of the binary lane already reads.
  const control = distillControlObservations(files);
  const controlPath = join(dirname(options.outPath), 'control-observations.json');

  // A cache written before the control lane existed carries no `controlMessages` key
  // at all, which is not the same as a cache that carries the key and found nothing.
  // Writing `symbols: []` for the first case publishes an absence as evidence — a
  // consumer cannot tell "the protocol has no subtypes" from "this cache predates the
  // lane". So the file is written only once the cache has actually been scanned for
  // them; until then, no file is better than a misleading one.
  //
  // `every`, not `some`. A PARTIALLY scanned cache is not "not ready yet", it is a
  // wrong-date generator: `distillControlObservations` would date each subtype from
  // the scanned entries alone, so a single scanned version at the tip dates the whole
  // control surface to the tip — anchored, and provably wrong against this lane's own
  // floors. `observedVersions` and the removal input are the full cache set, which is
  // only sound while the scanned set IS the full set. That is what this asserts.
  //
  // ⚠️ Being scanned is NOT sufficient to write. The release bot runs this on every
  // dispatch, from the committed cache — which IS fully scanned — so a scanned-only
  // gate would let the bot create this file, `scrape` attach the records, and the
  // whole control surface reach `data/` inside an auto-mergeable `chore(data)` PR.
  // That is the code-change-plus-regeneration the hard rules forbid, arriving through
  // the one channel with no review. So publishing has to be a deliberate act: pass
  // `--control` once, in the data PR. After that the file EXISTS, and the bot keeps
  // refreshing it — which is the steady state the workflow wants, since committed
  // evidence that stops tracking the cache is its own defect.
  const publishing = options.control || existsSync(controlPath);
  const unscanned = files.filter((file) => file.controlMessages === undefined);
  const refusal = !publishing
    ? `Skipped ${controlPath}: publishing control observations is opt-in. Pass ` +
      `--control to write it the first time; after that its presence is the opt-in ` +
      `and this runs on every backfill.`
    : unscanned.length > 0
      ? `Skipped ${controlPath}: ${unscanned.length} cache entry/entries carry no ` +
        `control-lane output, so dating would read from the scanned subset alone. ` +
        `Re-extract first.`
      : null;
  if (refusal) {
    console.log(refusal);
    console.log(
      `Distilled ${observations.symbols.length} binary symbol(s) from ${files.length} version(s) ` +
        `into ${options.outPath}; ${Object.keys(descriptions.descriptions).length} description ` +
        `timeline(s) into ${descPath}.`
    );
    // Keyed on `publishing`, not on the flag. Skipping while NOT publishing is the
    // normal path — the bot takes it on every run, and exit 0 is correct. Skipping
    // while publishing is a request that could not be honoured, and that includes the
    // steady state: once the file is committed, a refusal means the committed
    // observations have silently stopped tracking the cache. Nothing downstream
    // notices — every gate passes on a dataset with stale or absent control records.
    return publishing ? 1 : 0;
  }

  await writeFile(
    controlPath,
    `${JSON.stringify(
      {
        $generated_by: 'scripts/backfill-binary.ts',
        source: 'binary',
        note: CONTROL_NOTE,
        observedVersions: observations.observedVersions,
        symbols: control,
      },
      null,
      2
    )}\n`,
    'utf-8'
  );

  console.log(
    `Distilled ${observations.symbols.length} binary symbol(s) from ${files.length} version(s) ` +
      `into ${options.outPath}; ${Object.keys(descriptions.descriptions).length} description ` +
      `timeline(s) into ${descPath}; ${control.length} control_request subtype(s) into ` +
      `${controlPath}.`
  );
  return 0;
}

/* v8 ignore start -- CLI entry guard: false by construction when imported by tests */
if (isMain(import.meta.url)) {
  main(process.argv.slice(2))
    .then((code) => {
      process.exitCode = code;
    })
    .catch((error: unknown) => {
      console.error('Unexpected error while distilling binary observations:', error);
      process.exitCode = 1;
    });
}
/* v8 ignore stop */
