// Copyright 2026 Schuby
// SPDX-License-Identifier: Apache-2.0

/**
 * Binary lane — generator. Distils the per-version symbol extractions (produced
 * by `scripts/extract-bundle.ts` over every archived Claude Code binary) into
 * one committed, auditable evidence file: `data/binary-observations.json`.
 *
 * Evidence, not policy. This file records only *what was observed* — for each
 * own-evidenced symbol, the earliest and latest archived version whose bundle
 * contained it, plus the exact set of versions scanned (`observedVersions`).
 * The interpretation of that evidence (which symbols to publish, how to
 * categorize them, when to correct a `first_seen`) lives in the overlay,
 * `scripts/binary-lane.ts`, so the raw observations stay provenance-clean.
 *
 * `removed_in` is derived conservatively (see binary-lane's computeBinaryRemoval):
 * only a clean disappearance in the RELIABLE extraction era (< ~2.1.160) sets it.
 * Late-era absence is unreliable — the extractor's recall regressed around 2.1.160
 * (see scratch/audit-buckets.md), so a symbol last seen there is left present, and
 * the changelog remains the authority for confirmed (changelog/docs) symbols'
 * removals. Interior per-version on/off history is not encoded.
 *
 * Input = the per-version cache `scratch/binary-cache/<version>.json`, a
 * maintainer-local artifact (the 139 GB binary archive is not committed). Run
 * this to regenerate `data/binary-observations.json` when new versions are
 * archived; the committed output is what the build consumes, no re-download.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import {
  computeBinaryRemoval,
  type BinaryDescriptions,
  type BinaryObservation,
  type BinaryObservations,
  type DescriptionEra,
} from './binary-lane.js';
import { compareVersionsAsc, type ExtractedSymbolType, isMain } from './lib.js';

/** One per-version extraction file: `scratch/binary-cache/<version>.json`. */
export interface BinaryCacheFile {
  version: string;
  source?: string;
  count?: number;
  symbols: Array<{
    symbol: string;
    type: ExtractedSymbolType;
    category?: string;
    evidence?: string;
    description?: string;
  }>;
}

const NOTE =
  'Per-symbol observation window across archived Claude Code binaries. ' +
  'first_seen/last_seen are the earliest/latest scanned versions whose bundle ' +
  'contained the symbol (positive extraction evidence). removed_in is a conservative ' +
  'cliff-aware estimate: set only for a clean disappearance in the reliable extraction ' +
  'era (< ~2.1.160); later absence is untrusted (recall regressed there) and left null. ' +
  'Generated by scripts/backfill-binary.ts; interpreted by scripts/binary-lane.ts.';

const DEFAULT_CACHE_DIR = 'scratch/binary-cache';
const DEFAULT_OUT_PATH = 'data/binary-observations.json';

/** Sorts symbols deterministically by type then symbol name (matches other lanes). */
function compareObservations(a: BinaryObservation, b: BinaryObservation): number {
  if (a.type !== b.type) return a.type < b.type ? -1 : 1;
  return a.symbol < b.symbol ? -1 : a.symbol > b.symbol ? 1 : 0;
}

/**
 * Reduces the per-version cache files to one observation window per symbol.
 * Pure (no fs) so it is unit-testable against in-memory fixtures. A symbol's
 * `first_seen` is the numerically-earliest version it appears in, `last_seen`
 * the latest, and `removed_in` a conservative cliff-aware disappearance estimate
 * (see computeBinaryRemoval; null for symbols still present or too noisy to judge).
 * `observedVersions` is the full scanned set, newest first.
 */
export function distillObservations(files: BinaryCacheFile[]): BinaryObservations {
  const observedVersions = files
    .map((file) => file.version)
    .sort((a, b) => compareVersionsAsc(b, a));

  // Collect every version each symbol was seen in, then derive the window.
  const seenIn = new Map<string, { symbol: string; type: ExtractedSymbolType; versions: string[] }>();
  for (const file of files) {
    for (const { symbol, type } of file.symbols) {
      const key = `${type}:${symbol}`;
      const entry = seenIn.get(key);
      if (entry) entry.versions.push(file.version);
      else seenIn.set(key, { symbol, type, versions: [file.version] });
    }
  }

  const symbols: BinaryObservation[] = [];
  for (const { symbol, type, versions } of seenIn.values()) {
    const sorted = [...versions].sort(compareVersionsAsc);
    symbols.push({
      symbol,
      type,
      first_seen: sorted[0] as string,
      last_seen: sorted[sorted.length - 1] as string,
      removed_in: computeBinaryRemoval(versions, observedVersions),
    });
  }

  return {
    $generated_by: 'scripts/backfill-binary.ts',
    source: 'binary',
    note: NOTE,
    observedVersions,
    symbols: symbols.sort(compareObservations),
  };
}

const DESC_NOTE =
  'Per-symbol description timeline across archived Claude Code binaries: the ' +
  'command/skill registry description captured per version, collapsed to change ' +
  'points (eras). Each era holds from the given version until the next. Lets a ' +
  'snapshot carry the description the symbol actually had at that version instead ' +
  'of one current string. Generated by scripts/backfill-binary.ts; consumed by ' +
  'scripts/scrape-changelog.ts.';

/**
 * Distills a per-symbol description timeline from the cache: for every symbol that
 * carries a registry description, collect (version, description) across all cache
 * files and collapse consecutive-equal descriptions into eras (a new era only when
 * the text changes). A recall gap (a version that missed the symbol) is spanned by
 * the surrounding era — the same version-bounded imprecision as first_seen.
 */
/**
 * Collapse internal whitespace runs and trim. A cosmetic spacing change in the
 * source (e.g. "Maximum thinking tokens.  (only…" → "…tokens. (only…", a double
 * space becoming single) is NOT a real description change, so normalizing here
 * stops it spawning a spurious "duplicate-looking" era. cleanDescription (the
 * extractor) remains the authoritative content filter; this only tidies the
 * whitespace runs a minified bundle can leave behind.
 */
function normalizeDescriptionWhitespace(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

export function distillDescriptions(files: BinaryCacheFile[]): BinaryDescriptions {
  const seen = new Map<string, Array<{ version: string; description: string }>>();
  for (const file of files) {
    for (const s of file.symbols) {
      // The extractor (cleanDescription) is the authoritative description filter —
      // it drops backtick TEMPLATE literals but KEEPS a static quoted string that
      // merely contains "${". Don't re-filter `${` here: the cache no longer carries
      // the delimiter, so a broader `${` skip would wrongly drop a valid static one.
      if (!s.description) continue;
      const key = `${s.type}:${s.symbol}`;
      const arr = seen.get(key) ?? [];
      arr.push({ version: file.version, description: normalizeDescriptionWhitespace(s.description) });
      seen.set(key, arr);
    }
  }

  const descriptions: Record<string, DescriptionEra[]> = {};
  for (const key of [...seen.keys()].sort()) {
    const observations = [...(seen.get(key) as Array<{ version: string; description: string }>)].sort(
      (a, b) => compareVersionsAsc(a.version, b.version)
    );
    const eras: DescriptionEra[] = [];
    for (const obs of observations) {
      const last = eras[eras.length - 1];
      if (!last || last.description !== obs.description) {
        eras.push({ from: obs.version, description: obs.description });
      }
    }
    descriptions[key] = eras;
  }

  return {
    $generated_by: 'scripts/backfill-binary.ts',
    source: 'binary',
    note: DESC_NOTE,
    descriptions,
  };
}

/** Loads every `<version>.json` cache file from a directory. */
export async function loadCacheFiles(dir: string): Promise<BinaryCacheFile[]> {
  const names = (await readdir(dir)).filter((name) => name.endsWith('.json') && !name.startsWith('_'));
  const files = await Promise.all(
    names.map(async (name) => JSON.parse(await readFile(join(dir, name), 'utf-8')) as BinaryCacheFile)
  );
  if (files.length === 0) {
    throw new Error(
      `No cache files in ${dir}. The binary archive/cache is a maintainer-local artifact; ` +
        `rebuild it (see scratch/backfill-notes.md) before regenerating the observations.`
    );
  }
  return files;
}

interface CliOptions {
  cacheDir: string;
  outPath: string;
}

function parseArgs(argv: string[]): CliOptions {
  const options: CliOptions = { cacheDir: DEFAULT_CACHE_DIR, outPath: DEFAULT_OUT_PATH };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--cache' || arg === '--out') {
      const value = argv[i + 1];
      if (value === undefined) {
        throw new Error(`${arg} requires a path argument (e.g. "${arg} <dir>").`);
      }
      if (arg === '--cache') options.cacheDir = value;
      else options.outPath = value;
      i++;
    }
  }
  return options;
}

export async function main(argv: string[]): Promise<number> {
  const options = parseArgs(argv);
  const files = await loadCacheFiles(options.cacheDir);

  const observations = distillObservations(files);
  await writeFile(options.outPath, `${JSON.stringify(observations, null, 2)}\n`, 'utf-8');

  // The description timeline is written alongside the observations (same dir), so
  // a scratch --out during tests keeps both outputs out of committed data/.
  const descriptions = distillDescriptions(files);
  const descPath = join(dirname(options.outPath), 'binary-descriptions.json');
  await writeFile(descPath, `${JSON.stringify(descriptions, null, 2)}\n`, 'utf-8');

  console.log(
    `Distilled ${observations.symbols.length} binary symbol(s) from ${files.length} version(s) ` +
      `into ${options.outPath}; ${Object.keys(descriptions.descriptions).length} description ` +
      `timeline(s) into ${descPath}.`
  );
  return 0;
}

if (isMain(import.meta.url)) {
  main(process.argv.slice(2))
    .then((code) => {
      process.exitCode = code;
    })
    .catch((error: unknown) => {
      console.error('Unexpected error while distilling binary observations:', error);
      process.exitCode = 1;
    });
}
