#!/usr/bin/env node
// Copyright 2026 Schuby
// SPDX-License-Identifier: Apache-2.0

/**
 * Generates YAML and TOML exports from the committed JSON source of truth.
 *
 * The JSON files under `data/` (see `data/versions/*.json`, `data/index.json`,
 * `data/latest.json`, `data/schema-version.json`) are the single source of
 * truth (Section 7 "Output formats" of the plan). YAML and TOML are derived,
 * gitignored (`data/**\/*.yaml`, `data/**\/*.toml`) formats generated by this
 * script — at deploy time in CI (Section 5.4), or on demand locally.
 *
 * For every `<dir>/**\/*.json` file, this writes a sibling `<name>.yaml` and
 * `<name>.toml` (same path, extension replaced), overwriting any existing
 * file at that path.
 *
 * Usage:
 *   tsx scripts/generate-exports.ts [--data <dir>]
 *
 * `--data` defaults to `data`.
 */
import { readFile, writeFile } from 'node:fs/promises';

import { dump } from 'js-yaml';
import { stringify } from 'smol-toml';
import { glob } from 'tinyglobby';

import { isMain } from './lib.js';

/**
 * Serializes a value to YAML via `js-yaml`'s `dump`. YAML has a native null
 * type, so — unlike `toToml` — this is a straight, lossless serialization:
 * `null`-valued fields (e.g. `removed_in: null`, `source_url: null`) round-trip
 * exactly as `null`.
 */
export function toYaml(data: unknown): string {
  return dump(data);
}

/**
 * Recursively clones `value`, dropping any object key whose value is `null`.
 * Arrays are cloned element-for-element (an array *element* that is `null`
 * is preserved — only object *keys* are dropped, following the TOML
 * convention that an absent key means null/unset). Non-object, non-array
 * values pass through unchanged.
 */
export function stripNulls<T>(value: T): T {
  if (Array.isArray(value)) {
    return value.map((item) => stripNulls(item)) as unknown as T;
  }
  if (value !== null && typeof value === 'object') {
    const result: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(value as Record<string, unknown>)) {
      if (val === null) {
        continue;
      }
      result[key] = stripNulls(val);
    }
    return result as unknown as T;
  }
  return value;
}

/**
 * Serializes a value to TOML via `smol-toml`'s `stringify`.
 *
 * Critical asymmetry vs. `toYaml`: TOML has no null type, and `smol-toml`
 * throws on a `null` value. Our records commonly contain `removed_in: null`
 * and `source_url: null` (see `data/versions/*.json`). Per TOML convention,
 * an absent key represents "no value" / null, so — for the TOML path only —
 * the data is deep-cloned via `stripNulls` first, dropping every
 * null-valued object key before serialization. The input `data` itself is
 * never mutated, and `toYaml` is unaffected: it still receives (and
 * preserves) the original nulls.
 */
export function toToml(data: unknown): string {
  return stringify(stripNulls(data) as Record<string, unknown>);
}

function replaceExtension(filePath: string, newExt: string): string {
  return filePath.replace(/\.json$/, newExt);
}

async function generateExportsFor(filePath: string): Promise<void> {
  const raw = await readFile(filePath, 'utf-8');
  const data: unknown = JSON.parse(raw);

  const yamlPath = replaceExtension(filePath, '.yaml');
  const tomlPath = replaceExtension(filePath, '.toml');

  await writeFile(yamlPath, toYaml(data), 'utf-8');
  await writeFile(tomlPath, toToml(data), 'utf-8');
}

function parseArgs(argv: string[]): { dataDir: string } {
  let dataDir = 'data';
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--data') {
      const next = argv[i + 1];
      if (!next) {
        throw new Error('--data requires a directory argument');
      }
      dataDir = next;
      i++;
    }
  }
  return { dataDir };
}

export async function main(): Promise<number> {
  const { dataDir } = parseArgs(process.argv.slice(2));

  const files = await glob(`${dataDir}/**/*.json`, { absolute: false, dot: false });
  files.sort();

  if (files.length === 0) {
    console.log(`No JSON files found under "${dataDir}" (nothing to generate)`);
    return 0;
  }

  for (const filePath of files) {
    await generateExportsFor(filePath);
    console.log(
      `Generated ${replaceExtension(filePath, '.yaml')} and ${replaceExtension(filePath, '.toml')}`
    );
  }

  console.log(
    `Generated YAML and TOML exports for ${files.length} JSON file(s) under "${dataDir}".`
  );
  return 0;
}

// Only run the CLI when this file is executed directly (e.g. via `tsx
// scripts/generate-exports.ts` or `npm run generate-exports`), not when it's
// imported by tests or other modules.
if (isMain(import.meta.url)) {
  main()
    .then((code) => {
      process.exitCode = code;
    })
    .catch((err: unknown) => {
      console.error('Unexpected error while generating exports:', err);
      process.exitCode = 1;
    });
}
